allowBuilds:
  '@fortawesome/fontawesome-free': false
  esbuild: true
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - '@threatmap/quickjs-types'
  - '@threatmap/server-auth'
  - '@threatmap/schema-proxy'
  - '@threatmap/sdk-shared'
  - '@threatmap/quickssrf'
packages:
  - 'packages/*/*'
  - 'packages/server/server-auth/examples/*'
  - 'packages/sdk/sdk-client/examples/*'
  - 'tools/eslint-config'
