/* Generated by pnpm --filter @threatmap/tokens generate. Do not edit. */

export const dimensions = {
  spacing: 4,
  radius: 6,
} as const;

export const typeSteps = {
  caption: { size: 12, leading: 16, weight: 400 },
  body: { size: 14, leading: 20, weight: 400 },
  "body-strong": { size: 14, leading: 20, weight: 600 },
  heading: { size: 16, leading: 20, weight: 600 },
  title: { size: 18, leading: 24, weight: 600 },
  hero: { size: 24, leading: 32, weight: 600 },
} as const;

export const layers = {
  below: -1,
  base: 0,
  raised: 1,
  sticky: 2,
  overlay: 50,
  scrim: 60,
  spotlight: 70,
  floating: 100,
  detached: 10000,
  cover: 20000,
} as const;

export const icons = {
  marker: 12,
  message: 32,
} as const;
