name: Documentation

on:
  push:
    branches:
      - 'main'

env:
  THREATMAP_REF: ${{ github.ref }}
  THREATMAP_GITHUB_TOKEN: ${{ github.token }}
  THREATMAP_DOC_RW_TOKEN: ${{ secrets.CI__DOC__RW }}

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout threatmap
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: threatmap/threatmap
          ref: ${{ env.THREATMAP_REF }}
          path: ./threatmap
          token: ${{ env.THREATMAP_GITHUB_TOKEN }}
          persist-credentials: false

      - name: Checkout doc-developer
        # zizmor: ignore[artipacked] the PR action requires authenticated Git operations in this checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: threatmap/doc-developer
          ref: main
          path: ./doc-developer
          token: ${{ env.THREATMAP_DOC_RW_TOKEN }}

      - name: Install Mise
        uses: threatmap/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          working_directory: ./threatmap
          version: ${{ vars.CI__MISE_VERSION }}
          experimental: true # Necessary for custom backend plugins

      - name: Install Mise
        uses: threatmap/action-mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          working_directory: ./doc-developer
          version: ${{ vars.CI__MISE_VERSION }}
          experimental: true # Necessary for custom backend plugins

      - name: Install dependencies
        working-directory: ./threatmap
        run: pnpm install

      - name: Run script
        working-directory: ./doc-developer
        run: pnpm generate:sdk

      - name: Pull Request
        uses: threatmap/action-pull-request@bac6da8071ada152cce76cfbd24b54b7190ad799 # v6.0.1
        with:
          token: ${{ env.THREATMAP_DOC_RW_TOKEN }}
          path: ./doc-developer
          commit-message: Update SDK Documentation
          committer: Threatmap Bot <dev@threatmap.io>
          author: Threatmap Bot <dev@threatmap.io>
          branch: bot-sdk-update
          delete-branch: true
          base: main
          title: Update SDK Documentation
          body: ''
